### PR TITLE
Improved usability

### PR DESCRIPTION
**Pull request by nevrome**
This PR should introduce some more complete and more easily accessible documentation, most notably a file `janno_details.md` which explains the different columns in a `.janno` file

### CODE REVIEW

**Comment by stschiff** [comment]
I believe the documentation should rather go onto our dedicated homepage, as discussed. Right?

**Comment by nevrome** [comment]
Yes. I will move it there eventually.

As a general remark it sometimes might be difficult to separate definition and explanation.

**Comment by stschiff** [comment]
True.

**Comment by nevrome** [comment]
The important bits of this PR are on the homepage now. I'll close it and delete the branch.

**Pull request closed without merging**
