### PR TITLE
added Twist and Arbor capture types

### PR DESCRIPTION
**Pull request by stschiff**
I've just added the capture types discussed on Slack, plus the new Twist capture reagent. I've opted to call this `TwistAncientDNA` following [this preprint](https://www.biorxiv.org/content/10.1101/2022.01.13.476259v1.abstract)

### CODE REVIEW

**Comment by nevrome** [comment]
Note that this change has (off the top of my head) at least the following consequences:
- A new release of the schema has to be published
- The documentation on the website and the schema-software reference version list has to be updated
- poseidonR has to be updated (easy: just run the script in data-raw)
- poseidon-hs and all it's reverse dependencies have to be updated (easy: just add the constructors and update the instance definitions)
- All packages in the public repo have to be updated (easy: `trident update`)

Not difficult, but we have to remember to do all these things as soon as this is merged.

**Comment by stschiff** [comment]
Yes, OK. I will look into these todos and make sure they get added as issues once I merge this.

**Comment by nevrome** [comment]
I fear it's not enough to add these things as issues. In my opinion there should already be PRs ready. Happy to take over some of these ToDos.

**Comment by nevrome** [comment]
Very important addition to the ToDo list: We also need a tool to automatically update packages from 2.5.0 to 2.6.0. Should not be difficult.

**Comment by stschiff** [comment]
I have just moved the edits in this PR over to #51. I will close this.

**Pull request closed without merging**
