### PR TITLE
Update janno_columns.tsv

### PR DESCRIPTION
**Pull request by AyGhal**
Changed Data_Type description to allow for multiple values. E.g. Brunel et. al. 2020 with Shotgun and OtherCapture for each individual.

### CODE REVIEW

**Comment by wolfgangaroo** [comment]
I'm happy with the extension to multiple entries, especially since we will also produce papers that will include both 1240k and SG data.

**Review by wolfgangaroo — APPROVED** [review]

**Comment by stschiff** [comment]
Is this waiting for something? From my end this can be merged. Or has that been superseded now by #17

**Comment by nevrome** [comment]
This should not be merged if #17 is merged. #17 effectively contains this change.

**Comment by nevrome** [comment]
Part of #17

**Pull request closed without merging**
