### PR TITLE
changes for Poseidon 2.5.0

### LINKED ISSUE #43: Identifiers
The definition of `Individual_ID` seems inconsistent:

> The Individual_ID column has to represent each sample with a world-wide unique identifier string equal to the identifier used in the respective accompanying publication.

If `Individual_ID` has to *equal* the identifier used in the publication, how can one make sure it's also a UUID?
The specification goes on to say

> There is no central authority to issue these identifiers, so it remains in the hand of the authors to avoid duplication. The Individual_IDs are also employed in the genetic data files and therefore have to adhere to certain constraints. 

which might create even more problems to reconcile "identifier as in publication" with what Poseidon wants. From my experience, I'd recommend to distinguish *local IDs* and global UUIDs explicitly, and specify all of the constraints for the UUID.

### PR DESCRIPTION
**Pull request by nevrome**
I thought about the default column order and naming in the ,janno file.

```
No_of_Libraries -> Nr_Libraries
Data_Type -> Capture_Type
Nr_autosomal_SNPs -> Nr_SNPs
Publication_Status -> Publication
```

### CODE REVIEW

**Comment by stschiff** [comment]
Hmm, OK... I like making this all more consistent, but I'm a bit worried about the massive change this will require for existing janno files... I don't know, perhaps this isn't so bad, but one idea would be to wait until we have figured out a nice version guide or Automatic output of trident to help updating package version nrs.

But in principle I'm all for this change.

**Comment by nevrome** [comment]
Hm - we don't have to change the order in existing janno files, so we only have to rename some columns.

But you're right: this is a breaking change. I would like to get breaking changes in asap - before it's too late.

**Comment by stschiff** [comment]
Fair enough. Let's try and brain-storm about the handling of versions in trident than ASAP, so that it's easier to make these kinds of breaking changes in the future.

**Comment by nevrome** [comment]
Alright - I created a related PR to poseidon-hs already a while ago: https://github.com/poseidon-framework/poseidon-hs/pull/114. Not much in it, so far.

**Comment by stschiff** [comment]
I know. It's on my Todo-List to go through that one and contribute 😂... one step at a time.

**Comment by nevrome** [comment]
https://github.com/poseidon-framework/poseidon-hs/pull/114 is merged now, so this should become a main priority. Plus any other breaking changes we want to push through.

**Comment by stschiff** [comment]
There is one feature that I think is needed before we do this, and that is some way of finding suspicious column names with in Janno files. So if we - for example - go from `No_of_Libraries` to `Nr_Libraries`, it would be nice if we can spit out a warning that we found extra column that "look" like they could simply have the wrong name. Perhaps simply based on string overlap or so? Then, if we make such breaking changes, at least users will get a warning that their Janno files are not read the way a user might hope they are.

**Comment by nevrome** [comment]
That's a good idea. Some sort of fuzzy string matching should do the trick. Just like Microsoft's Clippy: "The .janno file has the column "No_of_Libraries". Did you mean "Nr_Libraries"?"

**Review by stschiff — COMMENTED** [review]
OK, I'm fine with all this. So if we merge this, the newest poseidon schema will be out of sync with both the most recent `poseidon-hs` and `published_data`. We need to organise a fluent transition somehow. I like your addition to `poseidonR` but we also need the fuzzy-matching warning in `poseidon-hs` before we update it to be compatible with this schema. 

It feels to me it'd be better to wait merging this until we are sure that our newest `trident` handles such a breaking change kindly. What do you think?

**Comment by nevrome** [comment]
Right. So the order of things would be the following:

- [x] Implement the fuzzy matching feature in poseidon-hs. It should be similar to the poseidonR implementation, which relies on a generalized Levenshtein (edit) distance.
- [ ] Go through the column names once more to consider more useful changes for this PR. Ideally we want to avoid having to do this too often!
- [x] Indicate the change in the [Changelog](https://poseidon-framework.github.io/#/changelog) and the [Version overview](https://poseidon-framework.github.io/#/version_table) table on the website
- [ ] Update the published_data repo with the new column names.
- [x] Update poseidon-hs and poseidonR with the new column names.

Did I forget something? Tricky to keep everything in mind.

**Comment by nevrome** [comment]
Additional renaming and new columns:
```
Individual_ID -> Poseidon_ID
Alternative_IDs
Relation_To
Relation_Type
Relation_Degree
Relation_Note
```

**Comment by nevrome** [comment]
Please put forward what else you would like to adjust for this new release, @stschiff, @AyGhal, @wolfgangaroo. As soon as @dhananjaya93 has the list of columns from the AADR we can discuss which ones we would like to take over.

**Comment by nevrome** [comment]
Additional new columns
```
Coverage_1240K -> Coverage_on_Target_SNPs
Date_Note
```
***

I'm at a loss regarding #46 and #47. I find our current solution for contamination estimates with the columns `X_Contam`, `X_Contam_Stderr`, `MT_Contam` and `MT_Contam_Stderr` unsatisfying, because it's not sufficiently precise and too many different kinds of estimates can go in there. Software-specific column names like `xContam_ANGSD` or `autContam_contamLD` on the other hand are also not a really future-proof solution. 

One idea to solve this once and for all, would be to offer four string list columns `Contamination`, `Contamination_Error`, `Contamination_Measure`, `Contamination_Note`. These could be used to dump all sorts of estimates in a more or less formalized manner. And people can decide themselves, which estimates they choose to equate.

| Contamination | Contamination_Error | Contamination_Measure            | Contamination_Note                                 |
|---------------|---------------------|----------------------------------|----------------------------------------------------|
| 0.1967;0;12   | 0.0067;0.01;3       | ANGSD v.123;Schmutzi v.321;Other | ;;Measured with a hot potato and three gummy bears |

For the `Contamindation_Measure` column we could define a standardized set of entries (e.g. `ANGSD v.123`; `Schmutzi v.321`, ...). In case of `other`, `Contamination_Note` could become mandatory, where free text entries are allowed (`I measured this with a red onion and a kitchen weight`).

I'm not sure if this is the way to go - I'm just brainstorming.

**Comment by stschiff** [comment]
I like it!

**Comment by nevrome** [comment]
I added this contamination documentation setup now. I think it's indeed better and more future proof. I set the column type for `Contamination` and `Contamination_Err` to String for two reasons: 1. There might be ordinal ways to express contamination ("heavy", "moderate", ...) and 2. we become a bit less opinionated about how error ranges should be reported. Happy to discuss that.

**Comment by nevrome** [comment]
```
X_Contam
X_Contam_Stderr
MT_Contam
MT_Contam_Stderr
->
Contamination
Contamination_Err
Contamination_Meas
Contamination_Note
```

**Comment by nevrome** [comment]
I wrote [a script](https://github.com/poseidon-framework/scripts/blob/main/janno24_to_janno25.R) to automatically update all .janno files in the public repo to the new version. I'll now work on PRs for poseidon-hs and poseidonR that reflect the changes. Their respective validation features should then allow to assess if the script behaves as expected.

**Comment by stschiff** [comment]
Great, looks good. I'll merge this

**Pull request merged**
