### PR TITLE
Idea for a better specification of source tissue.

### PR DESCRIPTION
**Pull request by AyGhal**
This is a minor change and could be part of a new version of the standard.

### CODE REVIEW

**Comment by nevrome** [comment]
Spelling mistake in the commit message is my fault. Shame on these apple computers and their crazy keyboards :laughing: 

Beyond that I'm not so sure about this solution any more, Ayshin. Ideally we would have an own column for the specific type of bone (phalanx, humerus, femur, etc.) and only keep the high level information in the Source_Tissue column. Maybe the latter even limited to a predefined set of choices.

But I also see how much work it is to modify this standard and subsequently all the packages. Eventually we will probably anyway become more relaxed and creative with the unchecked string columns to account for things we do not see now. Probably you already found a nice compromise by putting the specifics in parentheses.

What do you think @stschiff & @wolfgangaroo?

**Comment by AyGhal** [comment]
:smile: 
In previous editions I changed them to (e.g. tooth_incisor, tooth_molar, bone_cranial, bone_phalanx, bone_longbone, etc. and if there was no specifications as tooth, petrous, bone ). Is this okay or do we want to keep them in parenthesis or do something else?

**Comment by stschiff** [comment]
I would tend to keeping this as one column. What speaks against the underscore solution?

**Comment by nevrome** [comment]
Accepted by the poseidon core team today!

**Pull request merged**
